resources:

- name: ubuntu-image
  type: docker-image
  source: {repository: ubuntu}

- name: gdevops
  type: git
  source:
    uri: https://github.com/gerald-dev/gdevops.git

jobs:
- name: enum-vars-file
  plan:
  - in_parallel:
    - get: ubuntu-image
      params:
        globs: ["*image*"]
        unpack: true
    - get: gdevops
  - task: echo-vars
    image: ubuntu-image
    params:
      VARS_FILES: 
      - gdevops/vars/vars.yml
      - gdevops/1.txt
    file: gdevops/tasks/echo_vars.yml

